import os
import uuid
import subprocess
from pathlib import Path

from fastapi import FastAPI, UploadFile, File, Form
from fastapi.responses import HTMLResponse
from fastapi.responses import FileResponse, PlainTextResponse

APP_TITLE = "Transkun Web"
DATA_IN = Path("/data/in")
DATA_OUT = Path("/data/out")

app = FastAPI(title=APP_TITLE)


@app.get("/", response_class=HTMLResponse)
def index():
    return """
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Transkun Web</title>
    <style>
      body { font-family: system-ui, sans-serif; max-width: 820px; margin: 40px auto; padding: 0 16px; }
      .card { border: 1px solid #ddd; border-radius: 12px; padding: 18px; }
      input, select, button { font-size: 16px; }
      .row { margin: 12px 0; }
      code { background: #f5f5f5; padding: 2px 6px; border-radius: 6px; }
    </style>
  </head>
  <body>
    <h1>Transkun Web</h1>
    <div class="card">
      <form action="/transcribe" method="post" enctype="multipart/form-data">
        <div class="row">
          <label><b>Audio file:</b></label><br/>
          <input type="file" name="audio" required />
        </div>
        <div class="row">
          <label><b>Device:</b></label><br/>
          <select name="device">
            <option value="cuda" selected>cuda (GPU)</option>
            <option value="cpu">cpu</option>
          </select>
        </div>
        <div class="row">
          <button type="submit">Transcribe → MIDI</button>
        </div>
        <p style="color:#555;">
          Output is a <code>.mid</code> file generated by <code>transkun</code>.
        </p>
      </form>
    </div>
  </body>
</html>
"""


@app.post("/transcribe")
async def transcribe(
    audio: UploadFile = File(...),
    device: str = Form("cuda"),
):
    device = device.strip().lower()
    if device not in {"cuda", "cpu"}:
        return PlainTextResponse("Invalid device. Use 'cuda' or 'cpu'.", status_code=400)

    DATA_IN.mkdir(parents=True, exist_ok=True)
    DATA_OUT.mkdir(parents=True, exist_ok=True)

    suffix = Path(audio.filename or "").suffix
    if not suffix:
        suffix = ".audio"

    job_id = uuid.uuid4().hex
    in_path = DATA_IN / f"{job_id}{suffix}"
    out_path = DATA_OUT / f"{job_id}.mid"

    # Save upload
    content = await audio.read()
    in_path.write_bytes(content)

    cmd = ["transkun", str(in_path), str(out_path), "--device", device]

    try:
        proc = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )
        if proc.returncode != 0:
            # Return tool output for debugging
            return PlainTextResponse(
                f"transkun failed (exit {proc.returncode})\n\n{proc.stdout}",
                status_code=500,
            )
        if not out_path.exists():
            return PlainTextResponse("transkun finished but output .mid not found.", status_code=500)

        # Download result
        return FileResponse(
            path=str(out_path),
            media_type="audio/midi",
            filename=f"{Path(audio.filename or 'output').stem}.mid",
        )
    finally:
        # Keep the input file around for a short time? For now, delete input.
        # Output remains so you can inspect later; it sits under /data/out (bind-mounted).
        try:
            if in_path.exists():
                in_path.unlink()
        except Exception:
            pass
