services:
  breakglass-whoami:
    image: traefik/whoami:latest
    restart: unless-stopped
    networks: [proxy]
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      - traefik.http.routers.breakglass.rule=Host(`breakglass.${BASE_DOMAIN}`)
      - traefik.http.routers.breakglass.entrypoints=websecure
      - traefik.http.routers.breakglass.tls=true
        #      - traefik.http.routers.breakglass.middlewares=lan-allowlist@file
      - traefik.http.services.breakglass.loadbalancer.server.port=80

networks:
  proxy:
    external: true
