tunnel: 5ac248ab-ed34-4bfa-b904-3210c5871314
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: auth.timopoly.com
    service: https://gateway_traefik:443
    originRequest:
      originServerName: auth.timopoly.com
      # With a public LE cert this can stay TRUE (default), but explicit is nice:
      noTLSVerify: false

  - hostname: iptv.timopoly.com
    service: https://gateway_traefik:443
    originRequest:
      originServerName: iptv.timopoly.com
      noTLSVerify: false

  # add more apps like this:
  # - hostname: metube.timopoly.com
  #   service: https://gateway_traefik:443
  #   originRequest:
  #     originServerName: metube.timopoly.com
  #     noTLSVerify: false

  - service: http_status:404
