tunnel: 5618b03c-abe5-4504-ab37-a3e2f4c70820
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: auth.timopoly.com
    service: https://gateway_traefik:443
    originRequest:
      originServerName: auth.timopoly.com
      httpHostHeader: auth.timopoly.com
      noTLSVerify: true
      headers:
        X-Forwarded-Proto: "https"

  - hostname: iptv.timopoly.com
    service: https://gateway_traefik:443
    originRequest:
      originServerName: iptv.timopoly.com
      httpHostHeader: iptv.timopoly.com
      noTLSVerify: true
      headers:
        X-Forwarded-Proto: "https"

  - service: http_status:404
